database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "tracker"
  require_ssl: false
tracker:
  url: "wss://mainnet.infura.io/ws/v3/5d158c71773c4d869a97405bef38704f"
  abi_file_location: "./src/constants"